spring:
  profiles:
    active: test
    #include: mysql
    include: oracle
  redis:
    port: 6379
    host: 127.0.0.1
    client-type: jedis

mybatis: # 配置mybatis规则
  mapper-locations: classpath:mybatis/mapper/*.xml  # 指定sql映射文件的位置
  configuration: # 指定mybatis的全局配置
    map-underscore-to-camel-case: true   # 驼峰命名