spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/mytest
    url: jdbc:oracle:thin:@10.106.210.10:1521:orcl?characterEncoding=UTF-8
    username: idmstest0320
    password: idmstest0320
    driver-class-name: oracle.jdbc.driver.OracleDriver
    xa:
      properties:
        #设置useInformationSchema 可以获取tables表注释信息 即解决数据库表和列字段有说明、生成文档没有说明
        useInformationSchema: true