spring:
  datasource:
    url: jdbc:dm://10.41.16.179:5136?characterEncoding=UTF-8
    username: IAF_DEV
    password: Ji3#jg@0z8!S
    driver-class-name: dm.jdbc.driver.DmDriver
    xa:
      properties:
        #设置useInformationSchema 可以获取tables表注释信息 即解决数据库表和列字段有说明、生成文档没有说明
        useInformationSchema: true
