spring:
  datasource:
    url: jdbc:oracle:thin:@10.120.21.111:1521:orcl?characterEncoding=UTF-8
    username: test20230807
    password: test20230807
    driver-class-name: oracle.jdbc.driver.OracleDriver
    xa:
      properties:
        #设置useInformationSchema 可以获取tables表注释信息 即解决数据库表和列字段有说明、生成文档没有说明
        useInformationSchema: true