spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/mytest
    url: jdbc:mysql://10.159.140.111:3306/dip_ai_platform?characterEncoding=UTF-8
    username: root
    password: Xdcs@0901
    driver-class-name: com.mysql.cj.jdbc.Driver
    xa:
      properties:
        #设置useInformationSchema 可以获取tables表注释信息 即解决数据库表和列字段有说明、生成文档没有说明
        useInformationSchema: true